### ISSUE TITLE
Decorator interface for registering processing funcs?

### ISSUE THREAD

**Issue by tgoodlet** [elmotec/massedit#9]
What's your opinion on a using decorators to register processing functions?

It would eliminate the whole needing to have the `-f fixer:add_header` explicit syntax. Instead you just point to a module and the decorated funcs are auto loaded.

Also the requirement that the module is on the python path could be avoided by a simple [import of the file directly](http://stackoverflow.com/a/67692/4200924)

Whatcha think?

**Comment by elmotec** [comment]
I agree, the `-f fixer:add_header` is a little cryptic, one needs to remember the syntax and I seem to forget every time. 

So if I understand correctly, you propose to pass just a python file like `-f path/to/fixer.py` that would get loaded (wherever it is) and then use some magic decorator like say `@massedit` to let the script know about the program.

I'd like to keep the backward compatibility with `-f fixer` at least (provided fixer is in `$PYTHONPATH`, but yeah, sounds like a good idea.

**Comment by tgoodlet** [comment]
Yes exactly. Personally I'd go with a api something like,
```python
@massedit.processor
def my_processing_func(lines, path):
    for line in lines:
        ...
``` 
This lets you then do verification at import time with `inspect`:
- verify the function signature args
- verify that the `processor` is a generator

I can offer up a PR if you'd like.

**Comment by elmotec** [comment]
Yeah, that sounds good. I was hoping you'd offer :-)

**Comment by elmotec** [comment]
So I took a different approach and created an option `--generate` to generate a template fixer.py file. 

I found that most of the time the issue was not so much what function I should tell massedit.py to call (I had just created it) but what the callback should look like in the first place.

565bbd3fd46449884f4426ded6cc92f35eb3823a should fix that problem and allow the user to quickly see how to use massedit.
